/* Auto generated file. Do not edit by hand. This file was generated by SchemaHero. */

create table "action_queue" ("plan_id" text not null, "path" text not null, "created_at" timestamp not null, "started_at" timestamp, "completed_at" timestamp, primary key ("plan_id", "path"));
create table "bootstrap_chart" ("id" text not null, "workspace_id" text not null, "name" text not null);
create table "bootstrap_file" ("id" text not null, "chart_id" text, "workspace_id" text not null, "file_path" text not null, "content" text not null, "embeddings" vector (1024), primary key ("id"));
create table "bootstrap_meta" ("key" text not null, "value" text not null, "workspace_id" text not null, primary key ("key", "workspace_id"));
create table "bootstrap_revision" ("workspace_id" text not null, "revision_number" integer not null, "is_complete" boolean not null, primary key ("workspace_id", "revision_number"));
create table "bootstrap_workspace" ("id" text not null, "name" text not null, "current_revision" integer not null default '0', primary key ("id"));
create table "chartsmith_user" ("id" text not null, "email" text not null, "name" text not null, "image_url" text not null, "created_at" timestamp not null, "last_login_at" timestamp, "last_active_at" timestamp, "replicated_token" text, primary key ("id"));
create table "intent_queue" ("chat_message_id" text not null, "created_at" timestamp not null, "started_at" timestamp, "completed_at" timestamp, primary key ("chat_message_id"));
create table "notification_processing" ("notification_channel" text not null, "notification_id" text not null, "claimed_at" timestamp not null, "claimed_by" text not null, "processed_at" timestamp, "error" text, primary key ("notification_channel", "notification_id"));
create table "session" ("id" text not null, "user_id" text not null, "expires_at" timestamp not null, primary key ("id"));
create table "slack_notification" ("id" text not null, "created_at" timestamp not null, "user_id" text, "workspace_id" text, "notification_type" text not null, "additional_data" text, primary key ("id"));
create table "summarize_queue" ("file_id" text not null, "revision" integer not null, "created_at" timestamp not null, "started_at" timestamp, "completed_at" timestamp, primary key ("file_id", "revision"));
create table "summary_cache" ("content_sha256" text not null, "summary" text not null, "embeddings" vector (1024), primary key ("content_sha256"));
create table "workspace_chart" ("id" text not null, "workspace_id" text not null, "name" text not null, "revision_number" integer not null);
create table "workspace_chat" ("id" text not null, "workspace_id" text not null, "revision_number" integer not null, "created_at" timestamp not null, "sent_by" text not null, "prompt" text not null, "response" text, "is_intent_complete" boolean not null default 'false', "is_intent_conversational" boolean, "is_intent_plan" boolean, "is_intent_off_topic" boolean, "is_intent_chart_developer" boolean, "is_intent_chart_operator" boolean, "is_intent_proceed" boolean, primary key ("id"));
create table "workspace_file" ("id" text not null, "revision_number" integer null, "chart_id" text, "workspace_id" text not null, "file_path" text not null, "content" text not null, "embeddings" vector (1024), primary key ("id", "revision_number"));
create table "workspace_plan_action_file" ("plan_id" text not null, "path" text not null, "action" text not null, "status" text not null, "created_at" timestamp not null, primary key ("plan_id", "path"));
create table "workspace_plan" ("id" text not null, "workspace_id" text not null, "chat_message_ids" text[], "created_at" timestamp not null, "updated_at" timestamp not null, "version" integer, "status" text not null, "description" text, "charts_affected" text[], "files_affected" text[], "is_complete" boolean not null default 'false', primary key ("id"));
create table "workspace_rendered_chart" ("workspace_id" text not null, "revision_number" integer not null, "chart_id" text not null, "scenario_id" text not null, "is_success" boolean not null default 'false', primary key ("workspace_id", "revision_number", "chart_id", "scenario_id"));
create table "workspace_revision" ("workspace_id" text not null, "revision_number" integer not null, "created_at" timestamp not null, "plan_id" text, "created_by_user_id" text not null, "created_type" text not null, "is_complete" boolean not null, primary key ("workspace_id", "revision_number"));
create table "workspace_scenario" ("id" text not null, "workspace_id" text not null, "chart_id" text not null, "name" text not null, "description" text not null, "values" text, "is_read_only" boolean not null, primary key ("id"));
create table "workspace" ("id" text not null, "created_at" timestamp not null, "last_updated_at" timestamp, "name" text not null, "created_by_user_id" text not null, "created_type" text not null, "current_revision_number" integer not null, primary key ("id"));

